### ISSUE TITLE
Station.swift Model is missing, build fails

### ISSUE THREAD

**Issue by ggingell** [jillsands/OnTrack#1]
Good morning! I was attempting to build the project but it looks like there is a missing file. I don't often build in XCode so perhaps I am not running some setup step that is needed. 

```
Build target OnTrack of project OnTrack with configuration Debug

error: Build input file cannot be found: '/Users/grantgi/zillow/candidates/OnTrack/OnTrack/Models/Station.swift'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'OnTrack' from project 'OnTrack')
```

Thank you!

**Comment by jillsands** [comment]
I renamed a file and forgot to commit- sorry about that! It should build now :)
